name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Craftplacer.Windows.VisualStyles/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build -c Release --nologo Craftplacer.Windows.VisualStyles.sln
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: binaries
        path: './Craftplacer.Windows.VisualStyles/bin/Release/net5.0'
 
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'

    - name: Pack
      run: nuget pack './Craftplacer.Windows.VisualStyles/Craftplacer.Windows.VisualStyles.nuspec'
      
    - name: Upload NuGet package as artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: nuget
        path: './Craftplacer.Windows.VisualStyles.*.nupkg'
    
    - name: Push
      run: nuget push Craftplacer.Windows.VisualStyles.*.nupkg ${{ secrets.NuGetAPIKey }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
